version: '3.8'

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./database/loadData.sql:/docker-entrypoint-initdb.d/loadData.sql
    restart: unless-stopped
    ports:
      - "5432:5432"
  
  django:
    build:
      context: .
      dockerfile: ./docker/BackendDockerFile.dockerfile
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  vue:
    build:
      context: .
      dockerfile: ./docker/FrontendDockerFile.dockerfile
    container_name: vue
    command: ./docker/frontend.sh
    depends_on:
      - django
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    